# Generated by Django 4.0.6 on 2022-08-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TallyApp', '0002_delete_hi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Under',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
            ],
        ),
    ]
