# Generated by Django 4.0.6 on 2022-08-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TallyApp', '0006_rename_nature_maingroup_under_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maingroup',
            name='affect_gp',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
