# Generated by Django 4.0.6 on 2022-08-26 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TallyApp', '0008_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger_Banking_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_limit', models.CharField(blank=True, default='Null', max_length=225)),
                ('holder_name', models.CharField(blank=True, default='Null', max_length=225)),
                ('ac_number', models.CharField(blank=True, default='Null', max_length=225)),
                ('ifsc', models.CharField(blank=True, default='Null', max_length=225)),
                ('swift_code', models.CharField(blank=True, default='Null', max_length=225)),
                ('bank_name', models.CharField(blank=True, default='Null', max_length=225)),
                ('branch_name', models.CharField(blank=True, default='Null', max_length=225)),
                ('alter_chk_bks', models.CharField(blank=True, default='Null', max_length=225)),
                ('enbl_chk_printing', models.CharField(blank=True, default='Null', max_length=225)),
                ('auto_recoun', models.CharField(blank=True, default='Null', max_length=225)),
                ('ledger_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TallyApp.ledger')),
            ],
        ),
    ]
