# Generated by Django 4.0.6 on 2022-08-27 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TallyApp', '0012_remove_ledger_satutory_ledger_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='L_Tax_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_uin', models.CharField(blank=True, default='Null', max_length=225)),
                ('register_type', models.CharField(blank=True, default='Null', max_length=225)),
                ('pan_no', models.CharField(blank=True, default='Null', max_length=225)),
                ('alter_gst_details', models.CharField(blank=True, default='Null', max_length=225)),
                ('ledger_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TallyApp.ledger')),
            ],
        ),
        migrations.AddField(
            model_name='ledger_mailing_address',
            name='ledger_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TallyApp.l_tax_register'),
        ),
    ]
