# Generated by Django 4.0.6 on 2022-08-27 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TallyApp', '0013_l_tax_register_ledger_mailing_address_ledger_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger_tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_duty_or_tax', models.CharField(blank=True, default='Null', max_length=225)),
                ('type_of_tax', models.CharField(blank=True, default='Null', max_length=225)),
                ('valuation_type', models.CharField(blank=True, default='Null', max_length=225)),
                ('rate_per_unit', models.CharField(blank=True, default='Null', max_length=225)),
                ('Persentage_of_calculation', models.CharField(blank=True, default='Null', max_length=225)),
                ('ledger_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TallyApp.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger_sundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintain_balance_bill_by_bill', models.CharField(blank=True, default='Null', max_length=225)),
                ('Default_credit_period', models.CharField(blank=True, default='Null', max_length=225)),
                ('Check_for_credit_days', models.CharField(blank=True, default='Null', max_length=225)),
                ('ledger_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TallyApp.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger_Satutory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessable_calculation', models.CharField(blank=True, default='Null', max_length=225)),
                ('Appropriate_to', models.CharField(blank=True, default='Null', max_length=225)),
                ('gst_applicable', models.CharField(blank=True, default='Null', max_length=225)),
                ('Set_alter_GST', models.CharField(blank=True, default='Null', max_length=225)),
                ('type_of_supply', models.CharField(blank=True, default='Null', max_length=225)),
                ('Method_of_calc', models.CharField(blank=True, default='Null', max_length=225)),
                ('ledger_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TallyApp.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger_Rounding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rounding_Method', models.CharField(blank=True, default='Null', max_length=225)),
                ('Round_limit', models.CharField(blank=True, default='Null', max_length=22)),
                ('ledger_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TallyApp.ledger')),
            ],
        ),
        migrations.AddField(
            model_name='ledger_mailing_address',
            name='l_sundry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TallyApp.ledger_sundry'),
        ),
        migrations.AddField(
            model_name='ledger_mailing_address',
            name='l_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TallyApp.ledger_tax'),
        ),
        migrations.AddField(
            model_name='ledger_mailing_address',
            name='ledger_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TallyApp.ledger_rounding'),
        ),
        migrations.AddField(
            model_name='ledger_mailing_address',
            name='ledger_sat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TallyApp.ledger_satutory'),
        ),
    ]
