# Generated by Django 4.1 on 2022-08-29 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TallyApp', '0014_ledger_tax_ledger_sundry_ledger_satutory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='l_tax_register',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_banking_details',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_mailing_address',
            name='l_sundry',
        ),
        migrations.RemoveField(
            model_name='ledger_mailing_address',
            name='l_tax',
        ),
        migrations.RemoveField(
            model_name='ledger_mailing_address',
            name='ledger_bank',
        ),
        migrations.RemoveField(
            model_name='ledger_mailing_address',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_mailing_address',
            name='ledger_round',
        ),
        migrations.RemoveField(
            model_name='ledger_mailing_address',
            name='ledger_sat',
        ),
        migrations.RemoveField(
            model_name='ledger_mailing_address',
            name='ledger_tax',
        ),
        migrations.RemoveField(
            model_name='ledger_rounding',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_satutory',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_sundry',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_tax',
            name='ledger_id',
        ),
        migrations.AddField(
            model_name='ledger',
            name='l_sundry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TallyApp.ledger_sundry'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='l_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TallyApp.ledger_tax'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='ledger_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TallyApp.ledger_banking_details'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='ledger_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TallyApp.ledger_rounding'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='ledger_sat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TallyApp.ledger_satutory'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='ledger_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TallyApp.l_tax_register'),
        ),
    ]
