# Generated by Django 4.1 on 2022-08-29 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TallyApp', '0015_remove_l_tax_register_ledger_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='ledger_mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TallyApp.ledger_mailing_address'),
        ),
    ]
