# Generated by Django 4.1 on 2022-08-29 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TallyApp', '0018_alter_l_tax_register_ledger_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='lbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=100)),
                ('cross_using', models.CharField(max_length=200)),
                ('acno', models.IntegerField()),
                ('ifscode', models.CharField(max_length=200)),
                ('bankname', models.CharField(max_length=200)),
                ('ledger_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TallyApp.ledger')),
            ],
        ),
    ]
