# Generated by Django 4.1 on 2022-08-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TallyApp', '0019_lbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lbank',
            name='acno',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='lbank',
            name='bankname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lbank',
            name='cross_using',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lbank',
            name='ifscode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lbank',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
