# Generated by Django 4.1 on 2022-08-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TallyApp', '0020_alter_lbank_acno_alter_lbank_bankname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lbank',
            name='acno',
            field=models.IntegerField(blank=True, default='Null'),
        ),
        migrations.AlterField(
            model_name='lbank',
            name='bankname',
            field=models.CharField(blank=True, default='Null', max_length=200),
        ),
        migrations.AlterField(
            model_name='lbank',
            name='cross_using',
            field=models.CharField(blank=True, default='Null', max_length=200),
        ),
        migrations.AlterField(
            model_name='lbank',
            name='ifscode',
            field=models.CharField(blank=True, default='Null', max_length=200),
        ),
        migrations.AlterField(
            model_name='lbank',
            name='transaction_type',
            field=models.CharField(blank=True, default='Null', max_length=100),
        ),
    ]
