# Generated by Django 4.1 on 2022-08-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TallyApp', '0021_alter_lbank_acno_alter_lbank_bankname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lbank',
            name='acno',
            field=models.CharField(blank=True, default='Null', max_length=100),
        ),
    ]
