# Generated by Django 4.1 on 2022-08-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TallyApp', '0022_alter_lbank_acno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lbank',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
