# Generated by Django 4.1 on 2022-08-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TallyApp', '0024_alter_lbank_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger_banking_details',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_mailing_address',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_rounding',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_satutory',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_sundry',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_tax',
            name='ledger_id',
        ),
        migrations.AddField(
            model_name='ledger',
            name='bank_ac_number',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='bank_alter_chk_bks',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='bank_auto_recoun',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='bank_bank_name',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='bank_branch_name',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='bank_enbl_chk_printing',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='bank_holder_name',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='bank_ifsc',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='bank_od_limit',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='bank_swift_code',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='mail_address',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='mail_country',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='mail_name',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='mail_pincode',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='mail_state',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='rou_Round_limit',
            field=models.CharField(blank=True, default='Null', max_length=22),
        ),
        migrations.AddField(
            model_name='ledger',
            name='rou_Rounding_Method',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='sta_Appropriate_to',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='sta_Method_of_calc',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='sta_Set_alter_GST',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='sta_assessable_calculation',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='sta_gst_applicable',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='sta_type_of_supply',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='sun_Check_for_credit_days',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='sun_Default_credit_period',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='sun_maintain_balance_bill_by_bill',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='ta_Persentage_of_calculation',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='ta_rate_per_unit',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='ta_type_of_duty_or_tax',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='ta_type_of_tax',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='ta_valuation_type',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='tax_alter_gst_details',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='tax_gst_uin',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='tax_pan_no',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledger',
            name='tax_register_type',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.DeleteModel(
            name='L_Tax_Register',
        ),
        migrations.DeleteModel(
            name='Ledger_Banking_Details',
        ),
        migrations.DeleteModel(
            name='Ledger_Mailing_Address',
        ),
        migrations.DeleteModel(
            name='Ledger_Rounding',
        ),
        migrations.DeleteModel(
            name='Ledger_Satutory',
        ),
        migrations.DeleteModel(
            name='Ledger_sundry',
        ),
        migrations.DeleteModel(
            name='Ledger_tax',
        ),
    ]
