# Generated by Django 4.1 on 2022-08-31 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TallyApp', '0025_remove_ledger_banking_details_ledger_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='lcheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_no', models.CharField(max_length=100)),
                ('to_no', models.CharField(max_length=100)),
                ('no_cheques', models.CharField(max_length=100)),
                ('name_cheque', models.CharField(max_length=100)),
                ('ledger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TallyApp.ledger')),
            ],
        ),
    ]
