# Generated by Django 4.1 on 2022-08-31 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TallyApp', '0026_lcheque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Print_Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_width', models.CharField(max_length=100)),
                ('cheque_height', models.CharField(max_length=100)),
                ('cc_start_left', models.CharField(max_length=100)),
                ('cc_start_top', models.CharField(max_length=100)),
                ('cdate_dist_left', models.CharField(max_length=100)),
                ('cdate_dist_top', models.CharField(max_length=100)),
                ('date_style', models.CharField(max_length=100)),
                ('date_seprator', models.CharField(max_length=100)),
                ('date_sep_width', models.CharField(max_length=100)),
                ('date_dist', models.CharField(max_length=100)),
                ('party_dist_left', models.CharField(max_length=100)),
                ('party_dist_top', models.CharField(max_length=100)),
                ('party_width', models.CharField(max_length=100)),
                ('amount_dist_top', models.CharField(max_length=100)),
                ('amount_height_gap', models.CharField(max_length=100)),
                ('amount_dist2_top', models.CharField(max_length=100)),
                ('amount_start1_left', models.CharField(max_length=100)),
                ('amount_start2_left', models.CharField(max_length=100)),
                ('amount_width', models.CharField(max_length=100)),
                ('amount_currency', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('print_cname', models.CharField(max_length=100)),
                ('sign_first', models.CharField(max_length=100)),
                ('sign_second', models.CharField(max_length=100)),
                ('sign_dist_top', models.CharField(max_length=100)),
                ('sign_start_left', models.CharField(max_length=100)),
                ('sign_width', models.CharField(max_length=100)),
                ('sign_height', models.CharField(max_length=100)),
                ('ledger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TallyApp.ledger')),
            ],
        ),
    ]
