# Generated by Django 4.1 on 2022-09-01 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TallyApp', '0028_rename_amount_currency_print_cheque_amt_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print_cheque',
            name='ledger_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TallyApp.ledger'),
        ),
    ]
